### ISSUE TITLE
Error in assignedID: Technology with name "se-Biological-science-pack" doesn't exist

### ISSUE THREAD

**Issue by Protheus** [Aidiakapi/qol_research#5] opened 2020-05-27 18:06 UTC
Factorio: 0.18.27
qol_research: 3.1.0

When loading the mod, the below error is shows.

What should happen: loading without the se-Biological-science-pack error

![image](https://user-images.githubusercontent.com/1455178/83056172-3c25dc80-a055-11ea-9f05-4d0fe432ff06.png)

**Comment by Aidiakapi** [comment] 2020-05-27 18:23
This is caused by a rename in a pre-release version of Space Exploration. From QoL research v3.1.0, Earendel can edit the configuration himself, so expect to see an update from his end that fixes this.

I'm closing it because this is not an issue on this mod's side.

**Closed** 2020-05-27 19:29 UTC

**Comment by Aidiakapi** [comment] 2020-05-27 19:33
Sorry my bad, I misinterpreted what you meant. It's unlucky since this is identical to an issue reported to on the discussions page, that the last update sought to address.

It was caused by a refactor, it was doing a truthy check on a function, as opposed to calling the function and using the result: `if is_matching_override then` should have been `if is_matching_override(override) then`.
